server:
  port: 8080

spring:
  application:
    name: ecommerce

  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: YOUR_PROD_DB_USERNAME
    password: YOUR_PROD_DB_PASSWORD
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

security:
  jwt:
    secret-key: YOUR_PROD_SECRET_KEY
    expiration-time: 3600000

google:
  client_id: YOUR_GOOGLE_CLIENT_ID
  client_secret: YOUR_GOOGLE_CLIENT_SECRET
  redirect_uri: https://your-production-domain.com/auth/oauth2/callback/google
